name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Release
      run: |
          git clone https://github.com/VideoTogether/VideoTogether tmp
          cp -r ./tmp/release/ ./.vitepress/dist/
          rm -rf tmp

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: VideoTogether/VideoTogether.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build && find .
        BUILD_DIR: ./.vitepress/dist
